// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MTProtoFilter — фильтр, сортировка и пагинация для Telegram-прокси.
 */
export interface MTProtoFilter {
    "onlyWorking"?: boolean | null;
    "unchecked"?: boolean | null;

    /**
     * mtproto | socks
     */
    "type"?: string | null;
    "search"?: string | null;

    /**
     * ping|host|lastChecked
     */
    "sortBy": string;
    "sortDir": string;
    "limit": number;
    "offset": number;
}

/**
 * MTProtoProxy — Telegram-прокси (MTProto / tg-socks).
 */
export interface MTProtoProxy {
    "id": number;
    "host": string;
    "port": number;
    "secret"?: string;

    /**
     * mtproto | socks
     */
    "type": string;
    "pingMs"?: number | null;
    "method"?: string;
    "isWorking": boolean;
    "lastChecked"?: string | null;
    "sourceId"?: number | null;
}

/**
 * Proxy — запись пула прокси.
 */
export interface Proxy {
    "id": number;
    "host": string;
    "port": number;
    "protocol": string;
    "country"?: string | null;
    "city"?: string | null;
    "exitIp"?: string | null;
    "latitude"?: number | null;
    "longitude"?: number | null;
    "latencyMs"?: number | null;
    "downloadMbps"?: number | null;
    "lastChecked"?: string | null;
    "isWorking": boolean;
    "sourceId"?: number | null;
}

/**
 * ProxyFilter — фильтр, сортировка и пагинация для выборки пула.
 * Пагинация серверная; общее число строк возвращает CountProxies.
 */
export interface ProxyFilter {
    "onlyWorking"?: boolean | null;

    /**
     * true: last_checked IS NULL; false: IS NOT NULL
     */
    "unchecked"?: boolean | null;
    "protocol"?: string | null;
    "maxLatency"?: number | null;
    "country"?: string | null;

    /**
     * поиск по host
     */
    "search"?: string | null;

    /**
     * latency|host|lastChecked
     */
    "sortBy": string;

    /**
     * asc|desc
     */
    "sortDir": string;
    "limit": number;
    "offset": number;
}

/**
 * Source — источник списка прокси (URL, файл или ручной ввод без источника).
 */
export interface Source {
    "id": number;
    "name": string;
    "url"?: string | null;
    "filePath"?: string | null;
    "lastFetched"?: string | null;

    /**
     * ProxyCount не хранится в БД, а вычисляется через COUNT(*) по source_id.
     */
    "proxyCount": number;
    "createdAt": string;
}
