// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Source — источник списка прокси (URL, файл или ручной ввод без источника).
 */
export interface Source {
    "id": number;
    "name": string;
    "url"?: string | null;
    "filePath"?: string | null;
    "lastFetched"?: string | null;

    /**
     * ProxyCount не хранится в БД, а вычисляется через COUNT(*) по source_id.
     */
    "proxyCount": number;
    "createdAt": string;
}
