// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as MTProtoService from "./mtprotoservice.js";
import * as ProxyService from "./proxyservice.js";
import * as SettingsService from "./settingsservice.js";
import * as SourceService from "./sourceservice.js";
import * as TesterService from "./testerservice.js";
import * as ThemeService from "./themeservice.js";
export {
    MTProtoService,
    ProxyService,
    SettingsService,
    SourceService,
    TesterService,
    ThemeService
};

export type {
    FetchResult,
    MyLocation,
    Settings,
    TestCompleted,
    TestProgress,
    TestResult
} from "./models.js";
