// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FetchResult — итог загрузки/разбора источника.
 * Прокси автоматически раскладываются: обычные и Telegram (MTProto).
 */
export interface FetchResult {
    "sourceId": number;
    "fetched": number;
    "added": number;
    "skipped": number;
    "mtprotoFetched": number;
    "mtprotoAdded": number;
    "errors"?: string[] | null;
}

/**
 * MyLocation — местоположение пользователя (для расчёта расстояния до прокси).
 */
export interface MyLocation {
    "ip": string;
    "country": string;
    "city"?: string;
    "latitude"?: number | null;
    "longitude"?: number | null;
}

/**
 * Settings — пользовательские настройки приложения (camelCase для фронтенда).
 */
export interface Settings {
    "theme": string;
    "latencyTimeoutMs": number;
    "speedDownloadBytes": number;
    "testConcurrency": number;
    "copyFormat": string;
    "validateViaHttp": boolean;
    "httpValidationUrl": string;

    /**
     * SpeedTest включает измерение скорости в ходе обычной проверки.
     */
    "speedTest": boolean;
}

/**
 * TestCompleted — итог массовой проверки.
 */
export interface TestCompleted {
    "cancelled": boolean;
    "tested": number;
    "working": number;
}

/**
 * TestProgress — прогресс массовой проверки.
 */
export interface TestProgress {
    "total": number;
    "completed": number;
    "current": string;
}

/**
 * TestResult — результат проверки одного прокси.
 */
export interface TestResult {
    "proxyId": number;
    "latencyMs"?: number | null;
    "downloadMbps"?: number | null;
    "country"?: string | null;
    "city"?: string | null;
    "exitIp"?: string | null;
    "latitude"?: number | null;
    "longitude"?: number | null;
    "isWorking": boolean;
    "error"?: string;
}
