// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FetchResult — итог загрузки/разбора источника.
 */
export interface FetchResult {
    "sourceId": number;
    "fetched": number;
    "added": number;
    "skipped": number;
    "errors"?: string[] | null;
}
