// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MTProtoService — список, проверка, копирование и экспорт Telegram-прокси.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Cancel останавливает активную проверку.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(3486781717);
}

/**
 * CancelGeo останавливает определение гео.
 */
export function CancelGeo(): $CancellablePromise<void> {
    return $Call.ByID(3268440978);
}

/**
 * ClearStatus сбрасывает статус проверки под фильтр.
 */
export function ClearStatus(f: models$0.MTProtoFilter): $CancellablePromise<number> {
    return $Call.ByID(2071502182, f);
}

/**
 * ClearStatusByIDs сбрасывает статус у указанных прокси.
 */
export function ClearStatusByIDs(ids: number[] | null): $CancellablePromise<number> {
    return $Call.ByID(1219077603, ids);
}

/**
 * CopyToClipboard копирует ссылки tg:// выбранных прокси.
 */
export function CopyToClipboard(ids: number[] | null): $CancellablePromise<number> {
    return $Call.ByID(1738739687, ids);
}

/**
 * Count возвращает общее число Telegram-прокси под фильтр.
 */
export function Count(f: models$0.MTProtoFilter): $CancellablePromise<number> {
    return $Call.ByID(1789885778, f);
}

/**
 * Delete удаляет Telegram-прокси по ID.
 */
export function Delete(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(595775056, ids);
}

/**
 * DeleteByFilter удаляет Telegram-прокси под фильтр.
 */
export function DeleteByFilter(f: models$0.MTProtoFilter): $CancellablePromise<number> {
    return $Call.ByID(3465758607, f);
}

/**
 * ExportByFilter экспортирует Telegram-прокси по фильтру (потоково).
 */
export function ExportByFilter(f: models$0.MTProtoFilter, format: string, path: string): $CancellablePromise<number> {
    return $Call.ByID(3152457418, f, format, path);
}

/**
 * ExportByIDs экспортирует выбранные Telegram-прокси в файл.
 */
export function ExportByIDs(ids: number[] | null, format: string, path: string): $CancellablePromise<number> {
    return $Call.ByID(1857325314, ids, format, path);
}

/**
 * GetProxies возвращает страницу Telegram-прокси согласно фильтру.
 */
export function GetProxies(f: models$0.MTProtoFilter): $CancellablePromise<models$0.MTProtoProxy[] | null> {
    return $Call.ByID(631339699, f);
}

/**
 * LookupGeo определяет страну/город/координаты Telegram-прокси по IP сервера.
 * Идёт фоном с ограничением частоты запросов к гео-сервисам.
 */
export function LookupGeo(): $CancellablePromise<void> {
    return $Call.ByID(4111407594);
}

/**
 * PickExportPath открывает диалог сохранения файла.
 */
export function PickExportPath(format: string): $CancellablePromise<string> {
    return $Call.ByID(788425643, format);
}

/**
 * TestAll проверяет все Telegram-прокси.
 */
export function TestAll(): $CancellablePromise<void> {
    return $Call.ByID(1661348962);
}

/**
 * TestNonWorking проверяет проверенные, но нерабочие прокси.
 */
export function TestNonWorking(): $CancellablePromise<void> {
    return $Call.ByID(3580754701);
}

/**
 * TestProxies запускает проверку указанных Telegram-прокси.
 */
export function TestProxies(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(764499821, ids);
}

/**
 * TestUnchecked проверяет прокси без статуса.
 */
export function TestUnchecked(): $CancellablePromise<void> {
    return $Call.ByID(880783441);
}
