// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService — доступ фронтенда к пулу прокси (список, счётчик, удаление,
 * копирование в буфер и экспорт в файлы).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * ClearStatus сбрасывает результат проверки у прокси под фильтр.
 */
export function ClearStatus(f: models$0.ProxyFilter): $CancellablePromise<number> {
    return $Call.ByID(1523580093, f);
}

/**
 * ClearStatusByIDs сбрасывает результат проверки у указанных прокси.
 */
export function ClearStatusByIDs(ids: number[] | null): $CancellablePromise<number> {
    return $Call.ByID(1189830502, ids);
}

/**
 * CopyToClipboard копирует выбранные прокси в буфер обмена (формат из настроек).
 */
export function CopyToClipboard(ids: number[] | null): $CancellablePromise<number> {
    return $Call.ByID(2433293156, ids);
}

/**
 * CountProxies возвращает общее число прокси под фильтр.
 */
export function CountProxies(f: models$0.ProxyFilter): $CancellablePromise<number> {
    return $Call.ByID(2871247191, f);
}

/**
 * DeleteByFilter удаляет прокси под фильтр.
 */
export function DeleteByFilter(f: models$0.ProxyFilter): $CancellablePromise<number> {
    return $Call.ByID(3894787358, f);
}

/**
 * DeleteProxies удаляет прокси по ID.
 */
export function DeleteProxies(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(4066638259, ids);
}

/**
 * ExportByFilter экспортирует прокси по фильтру (потоково, для больших объёмов).
 */
export function ExportByFilter(filter: models$0.ProxyFilter, format: string, path: string): $CancellablePromise<number> {
    return $Call.ByID(1066515039, filter, format, path);
}

/**
 * ExportByIDs экспортирует выбранные прокси в файл.
 */
export function ExportByIDs(ids: number[] | null, format: string, path: string): $CancellablePromise<number> {
    return $Call.ByID(2917192177, ids, format, path);
}

/**
 * GetProxies возвращает страницу пула согласно фильтру (серверная пагинация).
 */
export function GetProxies(f: models$0.ProxyFilter): $CancellablePromise<models$0.Proxy[] | null> {
    return $Call.ByID(3966699194, f);
}

/**
 * PickExportPath открывает диалог сохранения файла и возвращает путь.
 */
export function PickExportPath(format: string): $CancellablePromise<string> {
    return $Call.ByID(659342258, format);
}
