// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService — доступ фронтенда к пулу прокси (список, счётчик, удаление).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CountProxies возвращает общее число прокси под фильтр.
 */
export function CountProxies(f: models$0.ProxyFilter): $CancellablePromise<number> {
    return $Call.ByID(2871247191, f);
}

/**
 * DeleteProxies удаляет прокси по ID.
 */
export function DeleteProxies(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(4066638259, ids);
}

/**
 * GetProxies возвращает страницу пула согласно фильтру (серверная пагинация).
 */
export function GetProxies(f: models$0.ProxyFilter): $CancellablePromise<models$0.Proxy[] | null> {
    return $Call.ByID(3966699194, f);
}
