// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService читает и сохраняет настройки.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearGeoCache очищает кэш гео (кнопка в настройках).
 */
export function ClearGeoCache(): $CancellablePromise<number> {
    return $Call.ByID(1274674327);
}

/**
 * Get возвращает настройки с подстановкой значений по умолчанию.
 */
export function Get(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(939948007);
}

/**
 * Update валидирует и сохраняет настройки, возвращает итоговое состояние.
 */
export function Update($in: $models.Settings): $CancellablePromise<$models.Settings> {
    return $Call.ByID(187242212, $in);
}
