// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourceService загружает списки прокси из URL, файлов и ручного ввода.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFromFile создаёт источник из локального файла.
 */
export function AddFromFile(name: string, path: string): $CancellablePromise<$models.FetchResult> {
    return $Call.ByID(1932912370, name, path);
}

/**
 * AddFromURL создаёт источник и загружает прокси по URL.
 */
export function AddFromURL(name: string, rawURL: string): $CancellablePromise<$models.FetchResult> {
    return $Call.ByID(261125981, name, rawURL);
}

/**
 * AddManual добавляет прокси из ручного ввода прямо в пул (без источника).
 */
export function AddManual(text: string): $CancellablePromise<$models.FetchResult> {
    return $Call.ByID(3260242666, text);
}

/**
 * DeleteSource удаляет источник (прокси остаются в пуле).
 */
export function DeleteSource(id: number): $CancellablePromise<void> {
    return $Call.ByID(3959797551, id);
}

/**
 * ListSources возвращает список источников.
 */
export function ListSources(): $CancellablePromise<models$0.Source[] | null> {
    return $Call.ByID(99762869);
}

/**
 * PickProxyFile открывает системный диалог выбора файла и возвращает путь.
 * Пустая строка означает, что пользователь отменил выбор.
 */
export function PickProxyFile(): $CancellablePromise<string> {
    return $Call.ByID(2733237558);
}

/**
 * RefreshSource повторно загружает источник (URL или файл).
 */
export function RefreshSource(id: number): $CancellablePromise<$models.FetchResult> {
    return $Call.ByID(1569381817, id);
}
