// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TesterService проверяет прокси: TCP-connect (latency) + HTTP через сам прокси.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel останавливает активную массовую проверку.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(256871081);
}

/**
 * TestNonWorking запускает проверку всех нерабочих прокси (асинхронно).
 */
export function TestNonWorking(): $CancellablePromise<void> {
    return $Call.ByID(1060913449);
}

/**
 * TestProxies запускает массовую проверку указанных прокси (асинхронно).
 */
export function TestProxies(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(603970985, ids);
}

/**
 * TestProxy проверяет один прокси синхронно и сохраняет результат.
 */
export function TestProxy(id: number): $CancellablePromise<$models.TestResult> {
    return $Call.ByID(3310604085, id);
}
