// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThemeService сообщает фронтенду системную тему и уведомляет её об изменениях.
 * Ручной выбор темы (System / Light / Dark) хранит и применяет фронтенд;
 * здесь — только источник истины для режима "system".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetSystemTheme возвращает "dark" или "light" по настройке ОС.
 */
export function GetSystemTheme(): $CancellablePromise<string> {
    return $Call.ByID(2350965029);
}
